"""
Sensitive Question Checker - Detects requests for sensitive database information
Uses ONLY Gemini AI - no hardcoded keywords or patterns
"""
from typing import Tuple, Optional
import logging
import re

from langchain_core.prompts import ChatPromptTemplate
from app.llm.gemini_client import gemini_client

logger = logging.getLogger(__name__)


# Prompt for detecting sensitive information requests - AI-based only, no hardcoded patterns
SENSITIVE_QUESTION_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are an intelligent security assistant that analyzes user questions to determine if they are requesting sensitive database structure information.

Your task is to:
1. Analyze the user's question carefully
2. Determine if they are asking for sensitive database structure information (schema, table names, column names, database name, etc.)
3. If sensitive, respond with "SENSITIVE"
4. If not sensitive, respond with "SAFE" (user is asking about data content, statistics, or business insights)

━━━━━━━━━━━━━━━━━━━━━━
🎯 CLASSIFICATION RULES
━━━━━━━━━━━━━━━━━━━━━━

SENSITIVE (respond "SENSITIVE"):
- Requests for database schema/structure information
- Requests for table names or list of tables
- Requests for column names or field names
- Requests for database name or connection details
- Requests for technical metadata about database structure
- Any question that asks about "how the database is organized" rather than "what data is in the database"

NOT SENSITIVE (respond "SAFE"):
- Questions about data content (e.g., "How many customers?", "Show top 10 sales")
- Questions asking for statistics or aggregations
- Questions asking for business insights or analysis
- Questions asking to visualize data
- Questions that are clearly about the data itself, not the database structure

━━━━━━━━━━━━━━━━━━━━━━
❓ USER QUESTION
━━━━━━━━━━━━━━━━━━━━━━
{{question}}

━━━━━━━━━━━━━━━━━━━━━━
📤 YOUR RESPONSE
━━━━━━━━━━━━━━━━━━━━━━

Respond with ONLY one word: SENSITIVE or SAFE"""),
    ("human", "{question}")
])

# Prompt for generating rejection message
REJECTION_MESSAGE_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are a polite security assistant. A user asked a sensitive question that cannot be answered.

Generate a polite, professional rejection message in the same language as the user's question.

The message should:
- Politely explain that you cannot provide sensitive database structure information
- Be respectful and professional
- Include examples of what the user CAN ask instead
- Use the same language as the user's question (Arabic or English)

User's question: {{question}}

Generate the rejection message:"""),
    ("human", "{question}")
])


class SensitiveQuestionChecker:
    """Checks if user questions request sensitive database information"""
    
    def __init__(self):
        if not gemini_client.is_available():
            logger.warning("Gemini client not available. Sensitive question checking will be skipped.")
            self._available = False
        else:
            self._available = True
    
    def check(self, question: str) -> Tuple[bool, Optional[str]]:
        """
        Check if question requests sensitive information
        
        Uses ONLY Gemini AI for intelligent classification - no hardcoded keywords or patterns.
        
        Args:
            question: User's question
        
        Returns:
            (is_sensitive, polite_rejection_message)
            - is_sensitive: True if question requests sensitive info
            - rejection_message: Professional message generated by Gemini explaining why the request is rejected (in user's language)
        """
        if not self._available:
            logger.warning("Gemini client not available. Cannot perform sensitive question detection.")
            return False, None
        
        try:
            # Format prompt - use improved prompt with JSON output
            messages = SENSITIVE_QUESTION_PROMPT.format_messages(question=question)
            
            # Invoke Gemini
            response = gemini_client.client.invoke(messages)
            result = response.content.strip().upper()
            
            # Check response
            is_sensitive = "SENSITIVE" in result
            
            if is_sensitive:
                # Generate polite rejection message using Gemini
                rejection_msg = self._generate_polite_rejection_with_gemini(question)
                logger.info(
                    f"Sensitive question detected (AI-based)",
                    extra={"question": question[:100]}
                )
                return True, rejection_msg
            else:
                logger.debug(f"Question passed sensitive check: {question[:100]}")
                return False, None
                
        except Exception as e:
            logger.error(
                f"Sensitive question check failed: {e}",
                extra={"question": question[:100]},
                exc_info=True
            )
            # If AI check fails, allow the request (fail open)
            return False, None
    
    def _generate_polite_rejection_with_gemini(self, question: str) -> str:
        """Generate polite rejection message using Gemini AI"""
        try:
            messages = REJECTION_MESSAGE_PROMPT.format_messages(question=question)
            response = gemini_client.client.invoke(messages)
            rejection_message = response.content.strip()
            
            # Clean up the response
            if rejection_message:
                # Remove quotes if present
                if rejection_message.startswith('"') and rejection_message.endswith('"'):
                    rejection_message = rejection_message[1:-1]
                elif rejection_message.startswith("'") and rejection_message.endswith("'"):
                    rejection_message = rejection_message[1:-1]
            
            return rejection_message if rejection_message else self._fallback_rejection(question)
            
        except Exception as e:
            logger.warning(f"Failed to generate rejection message with Gemini: {e}")
            return self._fallback_rejection(question)
    
    def _fallback_rejection(self, question: str) -> str:
        """Fallback rejection message if Gemini fails"""
        has_arabic = bool(re.search(r'[\u0600-\u06FF]', question))
        
        if has_arabic:
            return (
                "عذراً، لا يمكنني تزويدك بمعلومات حساسة عن هيكل قاعدة البيانات "
                "مثل أسماء الجداول أو الأعمدة أو اسم قاعدة البيانات. "
                "يمكنني مساعدتك في استخراج المعلومات والإحصائيات من البيانات نفسها. "
                "مثال: \"كم عدد العملاء؟\" أو \"اعرض أعلى 10 مبيعات\"."
            )
        else:
            return (
                "I apologize, but I cannot provide sensitive database structure information "
                "such as table names, column names, or database names. "
                "I can help you extract information and statistics from the data itself. "
                "For example: \"How many customers are there?\" or \"Show top 10 sales\"."
            )


# Global checker instance
sensitive_question_checker = SensitiveQuestionChecker()
